app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(`processData-useThreePointCalibration` = "FALSE")
app$setInputs(`processData-useThreePointCalibration` = "TRUE")
app$setInputs(`processData-useMemoryCorrection` = "FALSE")
app$setInputs(`processData-useMemoryCorrection` = "TRUE")
app$snapshot()
app$setInputs(`processData-driftAndCalibration` = "0")
app$setInputs(`processData-driftAndCalibration` = "2")
app$setInputs(`processData-driftAndCalibration` = "1")
app$setInputs(`processData-doProcess` = "click")
app$snapshot()
app$uploadFile(`processData-files` = "../../test_data/HIDS2041_IsoWater_20151127_143940.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(`processData-doProcess` = "click")
app$snapshot()
app$snapshot()
